# Site settings
title: Stephanie J. Spielman, Ph.D.
email: stephanie.spielman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description of my website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sjspielman.org" # the base hostname & protocol for your site
twitter_username: StephSpiel
github_username:  sjspielman

favicon: "images/favicon.ico"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
# job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
